import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/CartContext";
import WishlistContextProvider from "@/components/context/WishlistContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
        <CartContextProvider>
          <WishlistContextProvider>
        <Navbar/>

        {children}
        <Footer/>
        <Toaster />
        </WishlistContextProvider>
        </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
